name: Test
on:
  push:
    branches: [main]
defaults:
      run:
        working-directory: Java/githubAction
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '23'
          
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.7'

          
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2


      - name: Build gradle
        run: ./gradlew build
      - name: Ejecutnado tests
        run: ./gradlew test > ../../tmp/salidaEjecucion.txt
      - name: Actualizar readme con nuevos test
        run: python3 ../../tmp/updateReadme.py

      - name: Commit automático del README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Añadido la línea de test en el readme"
          file_pattern: '.'
      

